/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'store-credentials-to-db': EventHandler<never, never>
    'submit-credentials': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'credentials-submitted-signup'; data: never }>
  }
}